### ISSUE TITLE
Segmentation Fault When Using OpenMP with -fopenmp in makenek on ARM Architecture

### ISSUE THREAD

**Issue by travizjass** [AMDComputeLibraries/Nekbone#8]
I have been trying to run Nekbone on ARM architecture with OpenMP using compiler flags (-fopenmp) inside makenek file. I verified that the OMP_NUM_THREADS environment variable is set correctly in the slurm file. Running the application without the -fopenmp flag works correctly. Could you provide guidance on resolving this segmentation fault? Are there specific configurations or additional steps required to successfully run Nekbone with OpenMP on an ARM architecture? Thanking you in advance.

**Comment by dmcdougall** [comment]
Unfortunately you're asking for help in the wrong place.  This repository isn't maintained by the Nekbone application developers.  This repository was originally intended to be a fork of the [upstream](https://github.com/Nek5000/Nekbone) codebase where we implemented OpenMP AMD GPU offloading features.  The intention was to then contribute those features as pull requests to the upstream repository.  Unfortunately, the upstream repository has been archived by the Nekbone code owners, and so pull requests for new features are no longer possible.

You could try contacting the [Nekbone codeowners](https://github.com/Nek5000/Nekbone/graphs/contributors) instead for support.  I'd recommend trying to contact [Misun Min](https://github.com/misunmin).

If you have a specific question about AMD GPU offloading in OpenMP, then it's likely we'll be able to help.  But your problem appears to be related to an ARM-based architecture instead.

Sorry to be the bearer of bad news.

**Comment by travizjass** [comment]
Thanks anyways.
